services:
  platzi-market-db:
    image: postgres:16
    container_name: platzi-market-db-container
    ports:
      - "53322:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: platzi-market

volumes:
  postgresdb:
    driver: local
